apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-a-metrics
  namespace: moath-webapp-dev
  labels:
    app: backend-a-moath
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-a-moath
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-b-metrics
  namespace: moath-webapp-dev
  labels:
    app: backend-b-moath
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-b-moath
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
