apiVersion: v1
kind: Service
metadata:
  name: backend-a-moath-metrics
  labels:
    app: backend-a-moath
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: backend-a-moath
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b-moath-metrics
  labels:
    app: backend-b-moath
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: backend-b-moath
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-a-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-a-moath
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-b-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend-b-moath
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
