resources:
  - ../../base
  - ingress.yaml

namespace: moath-webapp-prod

configMapGenerator:
  - name: db-config-moath
    behavior: replace
    literals:
      - DB_HOST=pg-moath-prod.postgres.database.azure.com
      - DB_PORT=5432
      - DB_NAME=webappdb-moath-prod
      - DB_USER=pgadmin

secretGenerator:
  - name: postgres-secret-moath
    literals:
      - POSTGRES_PASSWORD=YourRealPasswordHere

images:
  - name: acrmoath.azurecr.io/backend-a
    newTag: latest
  - name: acrmoath.azurecr.io/backend-b
    newTag: latest
