apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-moath
  namespace: moath-webapp
data:
  DB_HOST: pg-moath-dev.postgres.database.azure.com
  DB_PORT: "5432"
  DB_NAME: webappdb
  DB_USER: pgadmin
