apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-restrict-moath
  namespace: moath-webapp
spec:
  podSelector:
    matchLabels:
      app: backend-a-moath
  policyTypes:
  - Ingress
  - Egress

  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: backend-b-moath

  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-a-ingress-only-moath
  namespace: moath-webapp
spec:
  podSelector:
    matchLabels:
      app: backend-a-moath
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
