apiVersion: v1
kind: Service
metadata:
  name: backend-a-moath
spec:
  selector:
    app: backend-a-moath
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend-b-moath
spec:
  selector:
    app: backend-b-moath
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
