resources:
  - ../../base
  - ingress.yaml

namespace: moath-webapp-qa

configMapGenerator:
  - name: db-config-moath
    behavior: replace
    literals:
      - DB_HOST=pg-moath-qa.postgres.database.azure.com
      - DB_PORT=5432
      - DB_NAME=webappdb-moath-qa
      - DB_USER=pgadmin

images:
  - name: acrmoath.azurecr.io/backend-a
    newTag: latest
  - name: acrmoath.azurecr.io/backend-b
    newTag: latest
