resources:
  - ../../base

images:
  - name: backend-a
    newName: acrmoath.azurecr.io/backend-a-moath
    newTag: latest
  - name: backend-b
    newName: acrmoath.azurecr.io/backend-b-moath
    newTag: latest
